// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/client_message.proto

package com.mycompany.midtermproject2.proto;

public final class ClientMessageOuterClass {
  private ClientMessageOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ClientMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.mycompany.midtermproject2.proto.ClientMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required .com.mycompany.midtermproject2.proto.ClientMessage.MsgType type = 1;</code>
     */
    boolean hasType();
    /**
     * <code>required .com.mycompany.midtermproject2.proto.ClientMessage.MsgType type = 1;</code>
     */
    com.mycompany.midtermproject2.proto.ClientMessageOuterClass.ClientMessage.MsgType getType();

    /**
     * <pre>
     * used in CHAT and NICK types
     * </pre>
     *
     * <code>optional string body = 2;</code>
     */
    boolean hasBody();
    /**
     * <pre>
     * used in CHAT and NICK types
     * </pre>
     *
     * <code>optional string body = 2;</code>
     */
    java.lang.String getBody();
    /**
     * <pre>
     * used in CHAT and NICK types
     * </pre>
     *
     * <code>optional string body = 2;</code>
     */
    com.google.protobuf.ByteString
        getBodyBytes();
  }
  /**
   * Protobuf type {@code com.mycompany.midtermproject2.proto.ClientMessage}
   */
  public  static final class ClientMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.mycompany.midtermproject2.proto.ClientMessage)
      ClientMessageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ClientMessage.newBuilder() to construct.
    private ClientMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ClientMessage() {
      type_ = 0;
      body_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ClientMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              com.mycompany.midtermproject2.proto.ClientMessageOuterClass.ClientMessage.MsgType value = com.mycompany.midtermproject2.proto.ClientMessageOuterClass.ClientMessage.MsgType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                type_ = rawValue;
              }
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              body_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.mycompany.midtermproject2.proto.ClientMessageOuterClass.internal_static_com_mycompany_midtermproject2_proto_ClientMessage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.mycompany.midtermproject2.proto.ClientMessageOuterClass.internal_static_com_mycompany_midtermproject2_proto_ClientMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.mycompany.midtermproject2.proto.ClientMessageOuterClass.ClientMessage.class, com.mycompany.midtermproject2.proto.ClientMessageOuterClass.ClientMessage.Builder.class);
    }

    /**
     * Protobuf enum {@code com.mycompany.midtermproject2.proto.ClientMessage.MsgType}
     */
    public enum MsgType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>CHAT = 0;</code>
       */
      CHAT(0),
      /**
       * <code>NICK = 1;</code>
       */
      NICK(1),
      ;

      /**
       * <code>CHAT = 0;</code>
       */
      public static final int CHAT_VALUE = 0;
      /**
       * <code>NICK = 1;</code>
       */
      public static final int NICK_VALUE = 1;


      public final int getNumber() {
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static MsgType valueOf(int value) {
        return forNumber(value);
      }

      public static MsgType forNumber(int value) {
        switch (value) {
          case 0: return CHAT;
          case 1: return NICK;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<MsgType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          MsgType> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<MsgType>() {
              public MsgType findValueByNumber(int number) {
                return MsgType.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.mycompany.midtermproject2.proto.ClientMessageOuterClass.ClientMessage.getDescriptor().getEnumTypes().get(0);
      }

      private static final MsgType[] VALUES = values();

      public static MsgType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private MsgType(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:com.mycompany.midtermproject2.proto.ClientMessage.MsgType)
    }

    private int bitField0_;
    public static final int TYPE_FIELD_NUMBER = 1;
    private int type_;
    /**
     * <code>required .com.mycompany.midtermproject2.proto.ClientMessage.MsgType type = 1;</code>
     */
    public boolean hasType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .com.mycompany.midtermproject2.proto.ClientMessage.MsgType type = 1;</code>
     */
    public com.mycompany.midtermproject2.proto.ClientMessageOuterClass.ClientMessage.MsgType getType() {
      com.mycompany.midtermproject2.proto.ClientMessageOuterClass.ClientMessage.MsgType result = com.mycompany.midtermproject2.proto.ClientMessageOuterClass.ClientMessage.MsgType.valueOf(type_);
      return result == null ? com.mycompany.midtermproject2.proto.ClientMessageOuterClass.ClientMessage.MsgType.CHAT : result;
    }

    public static final int BODY_FIELD_NUMBER = 2;
    private volatile java.lang.Object body_;
    /**
     * <pre>
     * used in CHAT and NICK types
     * </pre>
     *
     * <code>optional string body = 2;</code>
     */
    public boolean hasBody() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <pre>
     * used in CHAT and NICK types
     * </pre>
     *
     * <code>optional string body = 2;</code>
     */
    public java.lang.String getBody() {
      java.lang.Object ref = body_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          body_ = s;
        }
        return s;
      }
    }
    /**
     * <pre>
     * used in CHAT and NICK types
     * </pre>
     *
     * <code>optional string body = 2;</code>
     */
    public com.google.protobuf.ByteString
        getBodyBytes() {
      java.lang.Object ref = body_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        body_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, type_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, body_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, type_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, body_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.mycompany.midtermproject2.proto.ClientMessageOuterClass.ClientMessage)) {
        return super.equals(obj);
      }
      com.mycompany.midtermproject2.proto.ClientMessageOuterClass.ClientMessage other = (com.mycompany.midtermproject2.proto.ClientMessageOuterClass.ClientMessage) obj;

      boolean result = true;
      result = result && (hasType() == other.hasType());
      if (hasType()) {
        result = result && type_ == other.type_;
      }
      result = result && (hasBody() == other.hasBody());
      if (hasBody()) {
        result = result && getBody()
            .equals(other.getBody());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasType()) {
        hash = (37 * hash) + TYPE_FIELD_NUMBER;
        hash = (53 * hash) + type_;
      }
      if (hasBody()) {
        hash = (37 * hash) + BODY_FIELD_NUMBER;
        hash = (53 * hash) + getBody().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.mycompany.midtermproject2.proto.ClientMessageOuterClass.ClientMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.mycompany.midtermproject2.proto.ClientMessageOuterClass.ClientMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.mycompany.midtermproject2.proto.ClientMessageOuterClass.ClientMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.mycompany.midtermproject2.proto.ClientMessageOuterClass.ClientMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.mycompany.midtermproject2.proto.ClientMessageOuterClass.ClientMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.mycompany.midtermproject2.proto.ClientMessageOuterClass.ClientMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.mycompany.midtermproject2.proto.ClientMessageOuterClass.ClientMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.mycompany.midtermproject2.proto.ClientMessageOuterClass.ClientMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.mycompany.midtermproject2.proto.ClientMessageOuterClass.ClientMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.mycompany.midtermproject2.proto.ClientMessageOuterClass.ClientMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.mycompany.midtermproject2.proto.ClientMessageOuterClass.ClientMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.mycompany.midtermproject2.proto.ClientMessageOuterClass.ClientMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.mycompany.midtermproject2.proto.ClientMessageOuterClass.ClientMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.mycompany.midtermproject2.proto.ClientMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.mycompany.midtermproject2.proto.ClientMessage)
        com.mycompany.midtermproject2.proto.ClientMessageOuterClass.ClientMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.mycompany.midtermproject2.proto.ClientMessageOuterClass.internal_static_com_mycompany_midtermproject2_proto_ClientMessage_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.mycompany.midtermproject2.proto.ClientMessageOuterClass.internal_static_com_mycompany_midtermproject2_proto_ClientMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.mycompany.midtermproject2.proto.ClientMessageOuterClass.ClientMessage.class, com.mycompany.midtermproject2.proto.ClientMessageOuterClass.ClientMessage.Builder.class);
      }

      // Construct using com.mycompany.midtermproject2.proto.ClientMessageOuterClass.ClientMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        type_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        body_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.mycompany.midtermproject2.proto.ClientMessageOuterClass.internal_static_com_mycompany_midtermproject2_proto_ClientMessage_descriptor;
      }

      public com.mycompany.midtermproject2.proto.ClientMessageOuterClass.ClientMessage getDefaultInstanceForType() {
        return com.mycompany.midtermproject2.proto.ClientMessageOuterClass.ClientMessage.getDefaultInstance();
      }

      public com.mycompany.midtermproject2.proto.ClientMessageOuterClass.ClientMessage build() {
        com.mycompany.midtermproject2.proto.ClientMessageOuterClass.ClientMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.mycompany.midtermproject2.proto.ClientMessageOuterClass.ClientMessage buildPartial() {
        com.mycompany.midtermproject2.proto.ClientMessageOuterClass.ClientMessage result = new com.mycompany.midtermproject2.proto.ClientMessageOuterClass.ClientMessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.type_ = type_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.body_ = body_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.mycompany.midtermproject2.proto.ClientMessageOuterClass.ClientMessage) {
          return mergeFrom((com.mycompany.midtermproject2.proto.ClientMessageOuterClass.ClientMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.mycompany.midtermproject2.proto.ClientMessageOuterClass.ClientMessage other) {
        if (other == com.mycompany.midtermproject2.proto.ClientMessageOuterClass.ClientMessage.getDefaultInstance()) return this;
        if (other.hasType()) {
          setType(other.getType());
        }
        if (other.hasBody()) {
          bitField0_ |= 0x00000002;
          body_ = other.body_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasType()) {
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.mycompany.midtermproject2.proto.ClientMessageOuterClass.ClientMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.mycompany.midtermproject2.proto.ClientMessageOuterClass.ClientMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int type_ = 0;
      /**
       * <code>required .com.mycompany.midtermproject2.proto.ClientMessage.MsgType type = 1;</code>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .com.mycompany.midtermproject2.proto.ClientMessage.MsgType type = 1;</code>
       */
      public com.mycompany.midtermproject2.proto.ClientMessageOuterClass.ClientMessage.MsgType getType() {
        com.mycompany.midtermproject2.proto.ClientMessageOuterClass.ClientMessage.MsgType result = com.mycompany.midtermproject2.proto.ClientMessageOuterClass.ClientMessage.MsgType.valueOf(type_);
        return result == null ? com.mycompany.midtermproject2.proto.ClientMessageOuterClass.ClientMessage.MsgType.CHAT : result;
      }
      /**
       * <code>required .com.mycompany.midtermproject2.proto.ClientMessage.MsgType type = 1;</code>
       */
      public Builder setType(com.mycompany.midtermproject2.proto.ClientMessageOuterClass.ClientMessage.MsgType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        type_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>required .com.mycompany.midtermproject2.proto.ClientMessage.MsgType type = 1;</code>
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        type_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object body_ = "";
      /**
       * <pre>
       * used in CHAT and NICK types
       * </pre>
       *
       * <code>optional string body = 2;</code>
       */
      public boolean hasBody() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <pre>
       * used in CHAT and NICK types
       * </pre>
       *
       * <code>optional string body = 2;</code>
       */
      public java.lang.String getBody() {
        java.lang.Object ref = body_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            body_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * used in CHAT and NICK types
       * </pre>
       *
       * <code>optional string body = 2;</code>
       */
      public com.google.protobuf.ByteString
          getBodyBytes() {
        java.lang.Object ref = body_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          body_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * used in CHAT and NICK types
       * </pre>
       *
       * <code>optional string body = 2;</code>
       */
      public Builder setBody(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        body_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * used in CHAT and NICK types
       * </pre>
       *
       * <code>optional string body = 2;</code>
       */
      public Builder clearBody() {
        bitField0_ = (bitField0_ & ~0x00000002);
        body_ = getDefaultInstance().getBody();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * used in CHAT and NICK types
       * </pre>
       *
       * <code>optional string body = 2;</code>
       */
      public Builder setBodyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        body_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.mycompany.midtermproject2.proto.ClientMessage)
    }

    // @@protoc_insertion_point(class_scope:com.mycompany.midtermproject2.proto.ClientMessage)
    private static final com.mycompany.midtermproject2.proto.ClientMessageOuterClass.ClientMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.mycompany.midtermproject2.proto.ClientMessageOuterClass.ClientMessage();
    }

    public static com.mycompany.midtermproject2.proto.ClientMessageOuterClass.ClientMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<ClientMessage>
        PARSER = new com.google.protobuf.AbstractParser<ClientMessage>() {
      public ClientMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new ClientMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ClientMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ClientMessage> getParserForType() {
      return PARSER;
    }

    public com.mycompany.midtermproject2.proto.ClientMessageOuterClass.ClientMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_mycompany_midtermproject2_proto_ClientMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_mycompany_midtermproject2_proto_ClientMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\032proto/client_message.proto\022#com.mycomp" +
      "any.midtermproject2.proto\"\206\001\n\rClientMess" +
      "age\022H\n\004type\030\001 \002(\0162:.com.mycompany.midter" +
      "mproject2.proto.ClientMessage.MsgType\022\014\n" +
      "\004body\030\002 \001(\t\"\035\n\007MsgType\022\010\n\004CHAT\020\000\022\010\n\004NICK" +
      "\020\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_mycompany_midtermproject2_proto_ClientMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_mycompany_midtermproject2_proto_ClientMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_mycompany_midtermproject2_proto_ClientMessage_descriptor,
        new java.lang.String[] { "Type", "Body", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
