// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/server_message.proto

package com.mycompany.midtermproject2.proto;

public final class ServerMessageOuterClass {
  private ServerMessageOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ServerMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.mycompany.midtermproject2.proto.ServerMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required .com.mycompany.midtermproject2.proto.ServerMessage.MsgType type = 1;</code>
     */
    boolean hasType();
    /**
     * <code>required .com.mycompany.midtermproject2.proto.ServerMessage.MsgType type = 1;</code>
     */
    com.mycompany.midtermproject2.proto.ServerMessageOuterClass.ServerMessage.MsgType getType();

    /**
     * <pre>
     * Used in CHAT and INFO types
     * </pre>
     *
     * <code>optional string body = 2;</code>
     */
    boolean hasBody();
    /**
     * <pre>
     * Used in CHAT and INFO types
     * </pre>
     *
     * <code>optional string body = 2;</code>
     */
    java.lang.String getBody();
    /**
     * <pre>
     * Used in CHAT and INFO types
     * </pre>
     *
     * <code>optional string body = 2;</code>
     */
    com.google.protobuf.ByteString
        getBodyBytes();

    /**
     * <code>optional .com.mycompany.midtermproject2.proto.ServerMessage.ErrType code = 3;</code>
     */
    boolean hasCode();
    /**
     * <code>optional .com.mycompany.midtermproject2.proto.ServerMessage.ErrType code = 3;</code>
     */
    com.mycompany.midtermproject2.proto.ServerMessageOuterClass.ServerMessage.ErrType getCode();
  }
  /**
   * Protobuf type {@code com.mycompany.midtermproject2.proto.ServerMessage}
   */
  public  static final class ServerMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.mycompany.midtermproject2.proto.ServerMessage)
      ServerMessageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ServerMessage.newBuilder() to construct.
    private ServerMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ServerMessage() {
      type_ = 0;
      body_ = "";
      code_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ServerMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              com.mycompany.midtermproject2.proto.ServerMessageOuterClass.ServerMessage.MsgType value = com.mycompany.midtermproject2.proto.ServerMessageOuterClass.ServerMessage.MsgType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                type_ = rawValue;
              }
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              body_ = bs;
              break;
            }
            case 24: {
              int rawValue = input.readEnum();
              com.mycompany.midtermproject2.proto.ServerMessageOuterClass.ServerMessage.ErrType value = com.mycompany.midtermproject2.proto.ServerMessageOuterClass.ServerMessage.ErrType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(3, rawValue);
              } else {
                bitField0_ |= 0x00000004;
                code_ = rawValue;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.mycompany.midtermproject2.proto.ServerMessageOuterClass.internal_static_com_mycompany_midtermproject2_proto_ServerMessage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.mycompany.midtermproject2.proto.ServerMessageOuterClass.internal_static_com_mycompany_midtermproject2_proto_ServerMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.mycompany.midtermproject2.proto.ServerMessageOuterClass.ServerMessage.class, com.mycompany.midtermproject2.proto.ServerMessageOuterClass.ServerMessage.Builder.class);
    }

    /**
     * Protobuf enum {@code com.mycompany.midtermproject2.proto.ServerMessage.MsgType}
     */
    public enum MsgType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>CHAT = 0;</code>
       */
      CHAT(0),
      /**
       * <code>INFO = 1;</code>
       */
      INFO(1),
      /**
       * <code>ERR = 2;</code>
       */
      ERR(2),
      ;

      /**
       * <code>CHAT = 0;</code>
       */
      public static final int CHAT_VALUE = 0;
      /**
       * <code>INFO = 1;</code>
       */
      public static final int INFO_VALUE = 1;
      /**
       * <code>ERR = 2;</code>
       */
      public static final int ERR_VALUE = 2;


      public final int getNumber() {
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static MsgType valueOf(int value) {
        return forNumber(value);
      }

      public static MsgType forNumber(int value) {
        switch (value) {
          case 0: return CHAT;
          case 1: return INFO;
          case 2: return ERR;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<MsgType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          MsgType> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<MsgType>() {
              public MsgType findValueByNumber(int number) {
                return MsgType.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.mycompany.midtermproject2.proto.ServerMessageOuterClass.ServerMessage.getDescriptor().getEnumTypes().get(0);
      }

      private static final MsgType[] VALUES = values();

      public static MsgType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private MsgType(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:com.mycompany.midtermproject2.proto.ServerMessage.MsgType)
    }

    /**
     * Protobuf enum {@code com.mycompany.midtermproject2.proto.ServerMessage.ErrType}
     */
    public enum ErrType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>NICK_IN_USE = 0;</code>
       */
      NICK_IN_USE(0),
      /**
       * <code>BAD_REQUEST = 1;</code>
       */
      BAD_REQUEST(1),
      ;

      /**
       * <code>NICK_IN_USE = 0;</code>
       */
      public static final int NICK_IN_USE_VALUE = 0;
      /**
       * <code>BAD_REQUEST = 1;</code>
       */
      public static final int BAD_REQUEST_VALUE = 1;


      public final int getNumber() {
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static ErrType valueOf(int value) {
        return forNumber(value);
      }

      public static ErrType forNumber(int value) {
        switch (value) {
          case 0: return NICK_IN_USE;
          case 1: return BAD_REQUEST;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<ErrType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          ErrType> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<ErrType>() {
              public ErrType findValueByNumber(int number) {
                return ErrType.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.mycompany.midtermproject2.proto.ServerMessageOuterClass.ServerMessage.getDescriptor().getEnumTypes().get(1);
      }

      private static final ErrType[] VALUES = values();

      public static ErrType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private ErrType(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:com.mycompany.midtermproject2.proto.ServerMessage.ErrType)
    }

    private int bitField0_;
    public static final int TYPE_FIELD_NUMBER = 1;
    private int type_;
    /**
     * <code>required .com.mycompany.midtermproject2.proto.ServerMessage.MsgType type = 1;</code>
     */
    public boolean hasType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .com.mycompany.midtermproject2.proto.ServerMessage.MsgType type = 1;</code>
     */
    public com.mycompany.midtermproject2.proto.ServerMessageOuterClass.ServerMessage.MsgType getType() {
      com.mycompany.midtermproject2.proto.ServerMessageOuterClass.ServerMessage.MsgType result = com.mycompany.midtermproject2.proto.ServerMessageOuterClass.ServerMessage.MsgType.valueOf(type_);
      return result == null ? com.mycompany.midtermproject2.proto.ServerMessageOuterClass.ServerMessage.MsgType.CHAT : result;
    }

    public static final int BODY_FIELD_NUMBER = 2;
    private volatile java.lang.Object body_;
    /**
     * <pre>
     * Used in CHAT and INFO types
     * </pre>
     *
     * <code>optional string body = 2;</code>
     */
    public boolean hasBody() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <pre>
     * Used in CHAT and INFO types
     * </pre>
     *
     * <code>optional string body = 2;</code>
     */
    public java.lang.String getBody() {
      java.lang.Object ref = body_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          body_ = s;
        }
        return s;
      }
    }
    /**
     * <pre>
     * Used in CHAT and INFO types
     * </pre>
     *
     * <code>optional string body = 2;</code>
     */
    public com.google.protobuf.ByteString
        getBodyBytes() {
      java.lang.Object ref = body_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        body_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CODE_FIELD_NUMBER = 3;
    private int code_;
    /**
     * <code>optional .com.mycompany.midtermproject2.proto.ServerMessage.ErrType code = 3;</code>
     */
    public boolean hasCode() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional .com.mycompany.midtermproject2.proto.ServerMessage.ErrType code = 3;</code>
     */
    public com.mycompany.midtermproject2.proto.ServerMessageOuterClass.ServerMessage.ErrType getCode() {
      com.mycompany.midtermproject2.proto.ServerMessageOuterClass.ServerMessage.ErrType result = com.mycompany.midtermproject2.proto.ServerMessageOuterClass.ServerMessage.ErrType.valueOf(code_);
      return result == null ? com.mycompany.midtermproject2.proto.ServerMessageOuterClass.ServerMessage.ErrType.NICK_IN_USE : result;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, type_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, body_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeEnum(3, code_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, type_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, body_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(3, code_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.mycompany.midtermproject2.proto.ServerMessageOuterClass.ServerMessage)) {
        return super.equals(obj);
      }
      com.mycompany.midtermproject2.proto.ServerMessageOuterClass.ServerMessage other = (com.mycompany.midtermproject2.proto.ServerMessageOuterClass.ServerMessage) obj;

      boolean result = true;
      result = result && (hasType() == other.hasType());
      if (hasType()) {
        result = result && type_ == other.type_;
      }
      result = result && (hasBody() == other.hasBody());
      if (hasBody()) {
        result = result && getBody()
            .equals(other.getBody());
      }
      result = result && (hasCode() == other.hasCode());
      if (hasCode()) {
        result = result && code_ == other.code_;
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasType()) {
        hash = (37 * hash) + TYPE_FIELD_NUMBER;
        hash = (53 * hash) + type_;
      }
      if (hasBody()) {
        hash = (37 * hash) + BODY_FIELD_NUMBER;
        hash = (53 * hash) + getBody().hashCode();
      }
      if (hasCode()) {
        hash = (37 * hash) + CODE_FIELD_NUMBER;
        hash = (53 * hash) + code_;
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.mycompany.midtermproject2.proto.ServerMessageOuterClass.ServerMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.mycompany.midtermproject2.proto.ServerMessageOuterClass.ServerMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.mycompany.midtermproject2.proto.ServerMessageOuterClass.ServerMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.mycompany.midtermproject2.proto.ServerMessageOuterClass.ServerMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.mycompany.midtermproject2.proto.ServerMessageOuterClass.ServerMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.mycompany.midtermproject2.proto.ServerMessageOuterClass.ServerMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.mycompany.midtermproject2.proto.ServerMessageOuterClass.ServerMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.mycompany.midtermproject2.proto.ServerMessageOuterClass.ServerMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.mycompany.midtermproject2.proto.ServerMessageOuterClass.ServerMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.mycompany.midtermproject2.proto.ServerMessageOuterClass.ServerMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.mycompany.midtermproject2.proto.ServerMessageOuterClass.ServerMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.mycompany.midtermproject2.proto.ServerMessageOuterClass.ServerMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.mycompany.midtermproject2.proto.ServerMessageOuterClass.ServerMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.mycompany.midtermproject2.proto.ServerMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.mycompany.midtermproject2.proto.ServerMessage)
        com.mycompany.midtermproject2.proto.ServerMessageOuterClass.ServerMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.mycompany.midtermproject2.proto.ServerMessageOuterClass.internal_static_com_mycompany_midtermproject2_proto_ServerMessage_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.mycompany.midtermproject2.proto.ServerMessageOuterClass.internal_static_com_mycompany_midtermproject2_proto_ServerMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.mycompany.midtermproject2.proto.ServerMessageOuterClass.ServerMessage.class, com.mycompany.midtermproject2.proto.ServerMessageOuterClass.ServerMessage.Builder.class);
      }

      // Construct using com.mycompany.midtermproject2.proto.ServerMessageOuterClass.ServerMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        type_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        body_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        code_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.mycompany.midtermproject2.proto.ServerMessageOuterClass.internal_static_com_mycompany_midtermproject2_proto_ServerMessage_descriptor;
      }

      public com.mycompany.midtermproject2.proto.ServerMessageOuterClass.ServerMessage getDefaultInstanceForType() {
        return com.mycompany.midtermproject2.proto.ServerMessageOuterClass.ServerMessage.getDefaultInstance();
      }

      public com.mycompany.midtermproject2.proto.ServerMessageOuterClass.ServerMessage build() {
        com.mycompany.midtermproject2.proto.ServerMessageOuterClass.ServerMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.mycompany.midtermproject2.proto.ServerMessageOuterClass.ServerMessage buildPartial() {
        com.mycompany.midtermproject2.proto.ServerMessageOuterClass.ServerMessage result = new com.mycompany.midtermproject2.proto.ServerMessageOuterClass.ServerMessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.type_ = type_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.body_ = body_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.code_ = code_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.mycompany.midtermproject2.proto.ServerMessageOuterClass.ServerMessage) {
          return mergeFrom((com.mycompany.midtermproject2.proto.ServerMessageOuterClass.ServerMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.mycompany.midtermproject2.proto.ServerMessageOuterClass.ServerMessage other) {
        if (other == com.mycompany.midtermproject2.proto.ServerMessageOuterClass.ServerMessage.getDefaultInstance()) return this;
        if (other.hasType()) {
          setType(other.getType());
        }
        if (other.hasBody()) {
          bitField0_ |= 0x00000002;
          body_ = other.body_;
          onChanged();
        }
        if (other.hasCode()) {
          setCode(other.getCode());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasType()) {
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.mycompany.midtermproject2.proto.ServerMessageOuterClass.ServerMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.mycompany.midtermproject2.proto.ServerMessageOuterClass.ServerMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int type_ = 0;
      /**
       * <code>required .com.mycompany.midtermproject2.proto.ServerMessage.MsgType type = 1;</code>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .com.mycompany.midtermproject2.proto.ServerMessage.MsgType type = 1;</code>
       */
      public com.mycompany.midtermproject2.proto.ServerMessageOuterClass.ServerMessage.MsgType getType() {
        com.mycompany.midtermproject2.proto.ServerMessageOuterClass.ServerMessage.MsgType result = com.mycompany.midtermproject2.proto.ServerMessageOuterClass.ServerMessage.MsgType.valueOf(type_);
        return result == null ? com.mycompany.midtermproject2.proto.ServerMessageOuterClass.ServerMessage.MsgType.CHAT : result;
      }
      /**
       * <code>required .com.mycompany.midtermproject2.proto.ServerMessage.MsgType type = 1;</code>
       */
      public Builder setType(com.mycompany.midtermproject2.proto.ServerMessageOuterClass.ServerMessage.MsgType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        type_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>required .com.mycompany.midtermproject2.proto.ServerMessage.MsgType type = 1;</code>
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        type_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object body_ = "";
      /**
       * <pre>
       * Used in CHAT and INFO types
       * </pre>
       *
       * <code>optional string body = 2;</code>
       */
      public boolean hasBody() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <pre>
       * Used in CHAT and INFO types
       * </pre>
       *
       * <code>optional string body = 2;</code>
       */
      public java.lang.String getBody() {
        java.lang.Object ref = body_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            body_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * Used in CHAT and INFO types
       * </pre>
       *
       * <code>optional string body = 2;</code>
       */
      public com.google.protobuf.ByteString
          getBodyBytes() {
        java.lang.Object ref = body_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          body_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * Used in CHAT and INFO types
       * </pre>
       *
       * <code>optional string body = 2;</code>
       */
      public Builder setBody(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        body_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Used in CHAT and INFO types
       * </pre>
       *
       * <code>optional string body = 2;</code>
       */
      public Builder clearBody() {
        bitField0_ = (bitField0_ & ~0x00000002);
        body_ = getDefaultInstance().getBody();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Used in CHAT and INFO types
       * </pre>
       *
       * <code>optional string body = 2;</code>
       */
      public Builder setBodyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        body_ = value;
        onChanged();
        return this;
      }

      private int code_ = 0;
      /**
       * <code>optional .com.mycompany.midtermproject2.proto.ServerMessage.ErrType code = 3;</code>
       */
      public boolean hasCode() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional .com.mycompany.midtermproject2.proto.ServerMessage.ErrType code = 3;</code>
       */
      public com.mycompany.midtermproject2.proto.ServerMessageOuterClass.ServerMessage.ErrType getCode() {
        com.mycompany.midtermproject2.proto.ServerMessageOuterClass.ServerMessage.ErrType result = com.mycompany.midtermproject2.proto.ServerMessageOuterClass.ServerMessage.ErrType.valueOf(code_);
        return result == null ? com.mycompany.midtermproject2.proto.ServerMessageOuterClass.ServerMessage.ErrType.NICK_IN_USE : result;
      }
      /**
       * <code>optional .com.mycompany.midtermproject2.proto.ServerMessage.ErrType code = 3;</code>
       */
      public Builder setCode(com.mycompany.midtermproject2.proto.ServerMessageOuterClass.ServerMessage.ErrType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000004;
        code_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>optional .com.mycompany.midtermproject2.proto.ServerMessage.ErrType code = 3;</code>
       */
      public Builder clearCode() {
        bitField0_ = (bitField0_ & ~0x00000004);
        code_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.mycompany.midtermproject2.proto.ServerMessage)
    }

    // @@protoc_insertion_point(class_scope:com.mycompany.midtermproject2.proto.ServerMessage)
    private static final com.mycompany.midtermproject2.proto.ServerMessageOuterClass.ServerMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.mycompany.midtermproject2.proto.ServerMessageOuterClass.ServerMessage();
    }

    public static com.mycompany.midtermproject2.proto.ServerMessageOuterClass.ServerMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<ServerMessage>
        PARSER = new com.google.protobuf.AbstractParser<ServerMessage>() {
      public ServerMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new ServerMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ServerMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ServerMessage> getParserForType() {
      return PARSER;
    }

    public com.mycompany.midtermproject2.proto.ServerMessageOuterClass.ServerMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_mycompany_midtermproject2_proto_ServerMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_mycompany_midtermproject2_proto_ServerMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\032proto/server_message.proto\022#com.mycomp" +
      "any.midtermproject2.proto\"\206\002\n\rServerMess" +
      "age\022H\n\004type\030\001 \002(\0162:.com.mycompany.midter" +
      "mproject2.proto.ServerMessage.MsgType\022\014\n" +
      "\004body\030\002 \001(\t\022H\n\004code\030\003 \001(\0162:.com.mycompan" +
      "y.midtermproject2.proto.ServerMessage.Er" +
      "rType\"&\n\007MsgType\022\010\n\004CHAT\020\000\022\010\n\004INFO\020\001\022\007\n\003" +
      "ERR\020\002\"+\n\007ErrType\022\017\n\013NICK_IN_USE\020\000\022\017\n\013BAD" +
      "_REQUEST\020\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_mycompany_midtermproject2_proto_ServerMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_mycompany_midtermproject2_proto_ServerMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_mycompany_midtermproject2_proto_ServerMessage_descriptor,
        new java.lang.String[] { "Type", "Body", "Code", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
